### ISSUE TITLE
force file for benchmark 10

### ISSUE THREAD

**Issue by VicenteR** [sanguinariojoe/aquagpusph#5]
We guess this is not the place for posing this request since this is not an issue but ... we find no other better place for this question:

In Benchmark 9, tld, the fluid torque/moment is registered in motion.dat 5th column... There is also a Forces.dat file that we think has at least the same info regarding the moment but we have to check...

We are interested in registering this variable for the forced motion case, example benchmark 10. Is there an easy way to get this? 

Sorry for this maybe too easy question but we are starting with the code and cannot fly high yet.

thx

**Comment by VicenteR** [comment]
if we pick the first lines from both files, Forces.dat and Motion. dat... Torque is the 6th column of Forces.dat and it seemss it does not have an equivalent in Motion.dat..... ???

# t forces_F forces_M 
       5.755e-05 (     3.49618e-05,        -826.609) (               0,               0,     2.14577e-05,               0) 
       0.0001151 (     2.04742e-05,        -826.609) (               0,               0,     9.05991e-06,               0) 
      0.00017265 (     1.76802e-05,        -826.142) (               0,               0,     1.14441e-05,               0) 
       0.0002302 (      0.00010537,        -825.245) (               0,               0,     0.000127316,               0) 
      0.00028775 (      0.00065773,         -824.12) (               0,               0,     0.000249863,               0) 
       0.0003453 (     0.000522628,         -822.75) (               0,               0,     0.000305176,               0) 
      0.00040285 (     0.000721656,        -821.102) (               0,               0,     0.000470638,               0) 
       0.0004604 (      0.00120606,        -819.264) (               0,               0,     0.000746727,               0) 
      0.00051795 (     0.000852615,        -817.342) (               0,               0,     0.000798225,               0) 
       0.0005755 (       0.0006731,        -815.302) (               0,               0,      0.00121117,               0) 


0.0	0.0	0.0	0.0	0.0	1.3303756532e-06
5.75499798288e-05	0.0	0.0	1.4077523259e-14	-3.30961702275e-05	5.6171415963e-07
0.000115099959658	0.0	0.0	-7.61873586441e-09	-3.30960574502e-05	7.09533651388e-07
0.000172649946762	0.0	0.0	-3.80932752009e-09	-3.30955044774e-05	7.89356181485e-06
0.000230199919315	0.0	0.0	-1.14279634644e-08	-3.30940420099e-05	1.54914851009e-05
0.000287749891868	0.0	0.0	-7.61828200524e-09	-3.30919065163e-05	1.8920898583e-05
0.000345299864421	0.0	0.0	-1.52365942085e-08	-3.30889233737e-05	2.91795731755e-05
0.000402849836973	0.0	0.0	-1.14264739892e-08	-3.30842703988e-05	4.62970710942e-05
0.000460399809526	0.0	0.0	-1.9044056998e-08	-3.30783659592e-05	4.9489975936e-05

**Comment by sanguinariojoe** [comment]
Issue: _An important topic or problem for debate or discussion._

If you have a problem, then it is actually an issue, worth to be discussed. However, you are asking 2 different questions, and therefore you should opened 2 different issues ;-)

Anyway, regarding the first question, if you look for the Main.xml file you can find the following line (the path may be different):
`<Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/forces.xml" />`
When such preset is loaded, the forces variables are declared and computed.

Hint: Such preset is using the angular momentum conservation, and therefore can be used just for the computation of the total force on the whole boundary. If you want the forces on a specific boundary, then you should take a look to the cylinder example

Regarding the second question, remember that it is a 2D case, and therefore the forces (Forces.dat) are given as force per meter, while, in Motion.py the moment is defined as follows:
`M = aqua.get("forces_M")[2] * D`
That's why you cannot find the same values in both files

**Comment by VicenteR** [comment]
thank you for your answer Pepe (it's Vicente and Chou here). 

our idea at the moment is just to run benchmark 10 again and add that line with the hope that not only forces will be computed but will be stored in Forces.dat

In these regards, what we have done is get that case files from github in (correct us please if the procedure is not the correct on) downloading the whole AQUAGPUSPH zip file and extracting from it the folder 

spheric_testcase10_waveimpact

whiich we have renamed as

spheric_testcase10_waveimpact_20160310/

and included in the files tree at:

/home/vrbernal/aquagpusph_2d/examples/2D/spheric_testcase10_waveimpact_20160310/

if we now make the tree, as:

vrbernal@vrbernal-X555LJ:~/aquagpusph_2d/examples
/2D/spheric_testcase10_waveimpact_20160310$ cmake CMakeLists.txt 

WE GET!

-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.2)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/vrbernal/aquagpusph_2d/examples/2D/spheric_testcase10_waveimpact_20160310

WHICH SEEMS FINE..

BUT IF WE NOW RUN!

bash run.sh --run

run.sh: línea 15: /home/vrbernal/aquagpusph_2d/examples/2D/spheric_testcase10_waveimpact_20160310/Create.py: Permiso denegado
run.sh: línea 16: /home/vrbernal/aquagpusph_2d/examples/2D/spheric_testcase10_waveimpact_20160310/bin/AQUAgpusph2D: No existe el archivo o el directorio

THERE IS A PROBLEM WITH PERMISSIONS FROM Create.py

WE ARRANGED IT BY EXECUTING:

chmod +x Create.py

AND NOW IF WE RUN AGAIN

bash run.sh --run
Opening output file...
#############################################################
#                                                           #
#    #    ##   #  #   #                           #         #
#   # #  #  #  #  #  # #                          #         #
#  ##### #  #  #  # #####  ##  ###  #  #  ## ###  ###       #
#  #   # #  #  #  # #   # #  # #  # #  # #   #  # #  #      #
#  #   # #  #  #  # #   # #  # #  # #  #   # #  # #  #      #
#  #   #  ## #  ##  #   #  ### ###   ### ##  ###  #  #      #
#                            # #             #              #
#                          ##  #             #              #
#                                                           #
#############################################################


    Writing fluid particles...

    0%
    10%
    20%
    30%
    40%
    50%
    60%
    70%
    80%
    90%
    100%

    Writing the boundary elements...

    0%
    10%
    20%
    30%
    40%
    50%
    60%
    70%
    80%
    90%
    100%
run.sh: línea 16: /home/vrbernal/aquagpusph_2d/examples/2D/spheric_testcase10_waveimpact_20160310/bin/AQUAgpusph2D: No existe el archivo o el directorio

THERE IS A PROBLEM IN LINE 16. IF WE LOOK THERE, THIS IS THE LINE, BUT WE HAVE NO 
bin/AQUAgpusph2D folder

    /home/vrbernal/aquagpusph_2d/examples/2D/spheric_testcase10_waveimpact_20160310/bin/AQUAgpusph2D -i Main.xml

maybe we have done something wrong with the make or whatever... Any clue?... Sorry for this clumsy question. We are just starting. We have not been able yet to test the matter of this debate.

THX!


V & A.

**Comment by sanguinariojoe** [comment]
This is another different issue (try to be consistent please... 1 issue = 1 thread... Big threads with a lot of different issues will become useless for other people)

This time you are dealing with 2 problems at the same time, CMake (CMake is a little evil) and automatic examples. Explaining the whole conflict may be a little bit too much, so I'm just providing you a different approach to achieve your goal:

1. Download AQUAgpusph (the zip file or using `git clone` command) 
2. Assuming you extracted/cloned it in the following folder:
/home/vrbernal/aquagpusph
Enter on that folder and compile AQUAgpusph:
```
cd /home/vrbernal/aquagpusph
cmake -DAQUAGPUSPH_3D=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
make -j4
```
3. Duplicate the example:
`cp -r examples/2D/spheric_testcase10_waveimpact examples/2D/spheric_testcase10_waveimpact_20160310`
4. Right now your example is trying to use the XML files from the incorrect folder (/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact). To fix that replace such folder by the good one in the following files (Continue reading to know how to do that automatically):
```
/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact_20160310/run.sh
/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact_20160310/Create.py
/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact_20160310/Motion.py
/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact_20160310/plot_p.py
/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact_20160310/templates/Motion.xml
```
Hint: You can see all the files where such folder should be replaced with a grep command:
`grep -r "/home/vrbernal/aquagpusph/examples/2D/spheric_testcase10_waveimpact" ./`
Hint: You can use **sed** to do that automatically:
`find ./ -type f -print0 | xargs -0 sed -i 's/spheric_testcase10_waveimpact/spheric_testcase10_waveimpact_kk/g'`
5. Now you have your example ready! Your example is using the Script Create.py to load and configure the XML templates from templates folder. Therefore to add modules you should edit the files inside such folder. More specifically, you can add forces.xml and forces.report.xml to templates/Main.xml in order to compute the forces and print the file Forces.dat:
```
<?xml version="1.0" ?>
<!--
   #    ##   #  #   #
  # #  #  #  #  #  # #                          #
 ##### #  #  #  # #####  ##  ###  #  #  ## ###  ###
 #   # #  #  #  # #   # #  # #  # #  # #   #  # #  #
 #   # #  #  #  # #   # #  # #  # #  #   # #  # #  #
 #   #  ## #  ##  #   #  ### ###   ### ##  ###  #  #
                           # #             #
                         ##  #             #

Another QUAlity GPU-SPH, by CEHINAV.
    http://canal.etsin.upm.es/
Authors:
    Jose Luis Cercos-Pita
    Leo Miguel Gonzalez
    Antonio Souto-Iglesias
-->

<sphInput>
    <!-- In this file we will just include other XML definition files -->
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/basic.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/basic/domain.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/deltaSPH.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/deltaSPH-full.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/BI.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/elasticBounce.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/forces.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/variableTimeStep.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/basic/timing.report.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/basic/performance.report.xml" />
    <Include file="/home/pepe/SPH/Code/aquagpusph.cmake/resources/Presets/cfd/forces.report.xml" />
    <Include file="Settings.xml" />
    <Include file="SPH.xml" />
    <Include file="Time.xml" />
    <Include file="Fluids.xml" />
    <Include file="Motion.xml" />
    <Include file="Sensors.xml" />
</sphInput>
```

That's all! Enjoy your case computing forces!
